[Unit]
Wants=waverover-update.service
After=waverover-update.service
StartLimitIntervalSec=120
StartLimitBurst=5

[Service]
Environment=WAVEROVER_IDENTITY_FILE=/home/waverover/ros2_ws/src/waverover/config/robot_identity.yaml
Restart=always
RestartSec=5
