frame_id: robotics_lab
targets:
  - id: target_0
    position: [2.5, 0.0]
  - id: target_1
    position: [1.5, -1.5]
  - id: target_2
    position: [1.5, -1.0]
  - id: target_3
    position: [-2.0, 0.0]
