frame_id: robotics_lab
main_target_id: target_main

targets:
  - id: target_main
    position: [2.5, 0.0]
    weight: 10.0

  - id: target_secondary_1
    position: [1.5, -1.5]
    weight: 1.0

  - id: target_secondary_2
    position: [1.5, -1.0]
    weight: 1.0

  - id: target_secondary_3
    position: [-2.0, 0.0]
    weight: 1.0